---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webtop-data
  labels:
    {{- include "webtop.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeSize }}