apiVersion: v1
kind: Service
metadata:
  name: {{ include "webtop.fullname" . }}
  labels:
    {{- include "webtop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: https
  selector:
    {{- include "webtop.selectorLabels" . | nindent 4 }}
